### ISSUE TITLE
Bundle failed due to jar file name conflict

### ISSUE THREAD

**Issue by zerg000000** [EwenG/badigeon#18]
If I need to bundle some libraries where the library name and version is the same, the bundle will be failed. do we have some jar renaming stratergy should be applied to avoid this problem?

e.g.
```
{:deps {duct/core {:mvn/version "0.8.0"}
            ragtime/core {:mvn/version "0.8.0"}}
```

This will be failed since they both share the same jar name `core-0.8.0.jar`

**Comment by EwenG** [comment]
Thank you for reaching out.
I pushed a change to uniquify the names in case of conflict.
Let me know if it works better for you !

**Comment by zerg000000** [comment]
Hi, tested. The problem is solved. Thanks!
