### ISSUE TITLE
tools.deps api change

### ISSUE THREAD

**Issue by puredanger** [EwenG/badigeon#24]
Just wanted to drop a note that the newest version of tools.deps.alpha contains some api changes (moving towards getting out of alpha). So when you bump to tools.deps.alpha >= 0.9.745, you'll need to change your use of clojure.tools.deps.alpha.reader/slurp-deps to get that from clojure.tools.deps.alpha instead.

**Comment by puredanger** [comment]
Similar changes elsewhere... the clojure.tools.deps.alpha.reader namespace no longer exists and most of those functions migrated to clojure.tools.deps.alpha.

**Comment by EwenG** [comment]
Thank you, this has been fixed.
