### ISSUE TITLE
How to use badigeon?

### ISSUE THREAD

**Issue by theronic** [EwenG/badigeon#26]
I tried to follow the sample.clj file, but I'm struggling. I'm only trying to include a single .java file in my Clojure build using deps.edn.

This does not seem to work:

```
{:paths   ["src/main/clojure" "src/test"]
 :deps    {org.clojure/clojure {:mvn/version "1.10.1"}}
 :aliases {:build {:extra-paths "src/main/java"
                   :extra-deps  {badigeon/badigeon {:mvn/version "1.0"}}}
           :test  {:deps {midje {:mvn/version "1.5.0"}}}}}
```

A bare-bones hello world example with a .clj file and a .java file would go a long way :). Thanks!

**Comment by EwenG** [comment]
Here it is [badigeon-hello-world](https://github.com/EwenG/badigeon-hello-world)
