### ISSUE TITLE
Wrong number of args (3) passed to: badigeon.bundle/copy-directory

### ISSUE THREAD

**Issue by ak-coram** [EwenG/badigeon#27]
`badigeon.bundle/copy-dep-dependency` seems to call `badigeon.bundle/copy-directory` with only 3 arguments, but it now requires 4 (version 1.6):

https://github.com/EwenG/badigeon/blob/6928878a40ee100caa9816a25078593e68f4bc2d/src/badigeon/bundle.clj#L176

**Comment by EwenG** [comment]
Oops sorry, it should be fixed now :)

**Comment by ak-coram** [comment]
Thank you for the quick fix, 1.7 is now working for me.
