### ISSUE TITLE
Provide a slurp-edn function that looks into the resource paths as well?

### ISSUE THREAD

**Issue by hlolli** [EwenG/badigeon#6]
Hi again,

I've implemented a native library spitter (just like was already implemented in Overtone before I started hacking with it). But I had a problem with the slurp-deps function. After I made a jar, I realized that it only looked with io/file but not io/resource, so I copied over some of the function to make it work inside a jar on a classpath and as a file

https://github.com/overtone/overtone/blob/master/src/overtone/jna_path.clj#L10-L45

So it would basically be a request, to provide some sort of function that finds the current deps.edn no matter where it's located? (given that it can only be located in a jarfile or on disk :) )

**Comment by EwenG** [comment]
A deps.edn resource may conflict with other deps.edn files on the classpath.

If I understand well you want to extract the native dependencies of a jar dependency of the current process and you are running into issues when the project does not use tools.deps.

A potential solution would be to introduce an "extract-native-dependencies" function that would work on a single jar file. Then you would have to compute the path of the jar you want to extract the native dependencies from. This could be done by searching the native dependencies themselves on the classpath. For example: (io/resource "native/linux/x86_64/libcelt0.so.2")

Would that solve you problem ?

**Comment by hlolli** [comment]
Yes that would work. With this, you're trying to avoid extracting the same
jar twice if it's found twice on the classpath? I wonder if giving the
jar-name once and extract the topmost occurrence of the tree would be
sufficient? Then the version number wouldn't even be needed, if a user
loads a library with an old version of native dependencies but chooses to
manually add newer version to his/her dependencies, his/her newer version
would then overwrite that deeper occurrence.

**Comment by EwenG** [comment]
That is not what I was thinking about.
The issue with using a deps.edn file as a classpath resource is that two different dependencies may both contain a deps.edn file. I such a case, the deps.edn file chosen by the jvm is not defined. So the classpath computed from the deps.edn file may not be the one you were expected.
A solution would be to make the deps.edn file path unique, let's say by adding a uuid to it.
But then why not querying one of the native dependencies directly since its path is already probably unique.

**Comment by hlolli** [comment]
Yes I agree, I don't see a reason in this case to fetch the deps.edn anyway. In my case, I'd just specify overtone/sc-synths and this will be on the classpath?

**Comment by EwenG** [comment]
I pushed a badigeon.bundle/extract-native-dependencies-from-file function on master. Could you try it and let me know if it fits your needs?
The path of a jar file with native dependencies can be computed like that:
(badigeon.utils/jar-entry->jar-file-path (clojure.java.io/resource "native/linux/x86_64/libcelt0.so.2"))

**Comment by hlolli** [comment]
I'll try asap, but an off-topic question, I'm trying to compile another project into a jar, and I'm importing clojure.lang.Var, but that class is never imported into the jar (actually nothing from clojure.lang is)

```
  (compile/compile '[panaeolus.all clojure.core clojure.main]
                   {:compile-path "target/classes"
                    :compiler-options {:disable-locals-clearing false
                                       :direct-linking false}
                    :classpath (classpath/make-classpath {:aliases []})})
  (println "making a jar")
  (jar/jar 'panaeolus.panaeolus {:mvn/version +version+}
           {:out-path (str "target/panaeolus-" +version+ ".jar")
            :main 'panaeolus.all
            :manifest {"Project-awesome-level" "super-great"
                       :my-section-1 [["MyKey1" "MyValue1"] ["MyKey2" "MyValue2"]]
                       :my-section-2 {"MyKey3" "MyValue3" "MyKey4" "MyValue4"}}
            :paths ["src" "target/classes"]
            :deps '{org.clojure/clojure {:mvn/version "1.10.0"}}
            :mvn/repos '{"clojars" {:url "https://repo.clojars.org/"}
                         "bintray" {:url "http://jcenter.bintray.com"}}
            :allow-all-dependencies? true})
```

also when I run bundle/bundle I get

```
Exception in thread "main" java.nio.file.DirectoryNotEmptyException: /home/hlolli/panaeolus/panaeolus/target/panaeolus-0.4.0-SNAPSHOT
	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:586)
	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:254)
	at java.base/java.nio.file.Files.copy(Files.java:1294)
	at badigeon.bundle$make_directory_file_visitor$reify__889.visitFile(bundle.clj:49)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
	at badigeon.bundle$copy_directory.invokeStatic(bundle.clj:103)
	at badigeon.bundle$copy_directory.invoke(bundle.clj:96)
	at badigeon.bundle$copy_dependency.invokeStatic(bundle.clj:140)
	at badigeon.bundle$copy_dependency.invoke(bundle.clj:130)
	at badigeon.bundle$bundle$fn__957.invoke(bundle.clj:179)
	at badigeon.bundle$bundle.invokeStatic(bundle.clj:174)
	at badigeon.bundle$bundle.invoke(bundle.clj:147)
	at compile_jar$_main.invokeStatic(compile_jar.clj:34)
	at compile_jar$_main.invoke(compile_jar.clj:12)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:491)
	at clojure.main$main_opt.invoke(main.clj:487)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
```

code

```
  (println "Bundle panaeolus..")
  (bundle/bundle
   (bundle/make-out-path 'panaeolus/panaeolus +version+)
   {:deps-map (deps-reader/slurp-deps "deps.edn")
    ;; :excluded-libs #{'org.clojure/clojure}
    :allow-unstable-deps? true
    :libs-path "lib"
    })
```

**Comment by EwenG** [comment]
clojure classes are not AOT compiled by badigeon.compile/compile because clojure comes already AOT compiled, badigeon.compile/compile relies on clojure.core/compile and clojure.core/compile does not compile already AOT compiled code. You have to rely on the "slim" version of the clojure dependency if you want it to be AOT compiled by badigeon.compile/compile

See here [here](https://github.com/EwenG/badigeon/issues/3) for more details.

I will try to make it clearer in the docstrings

I will have a look at the second error

**Comment by hlolli** [comment]
I'm not sure but I wouldn't be surprised that slim wont work either because it's a java file originally? https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/Var.java

in deps.edn I added `org.clojure/clojure$slim     {:mvn/version "1.10.0"}` (classifier isn't allowed as keyword anymore).

```
:classifier in Maven coordinates is no longer supported.
Use groupId/artifactId$classifier in lib names instead.
```

ans also in :deps in jar.

But I feel like this shouldn't be a compile thing, but a jar/jar task, to take all the classfiles from the classpath and put them into the jar, I did manually add clojure.lang classfiles dir into target/classes and then created a jar, that solved my first problem then I got another one

```
Exception in thread "main" java.lang.NoClassDefFoundError: clojure/asm/Opcodes
```

**Comment by hlolli** [comment]
Sorry I take that back, it actually should be from the compile, all other class files are from there and jar only takes project's local files, if I understand the idea correctly.

**Comment by EwenG** [comment]
Yes you are right you will still be missing classes compiled from java source files (clojure.lang ...). I will try to figure out a way to extract compiled classes from dependencies.

**Comment by EwenG** [comment]
Do you still have the "java.nio.file.DirectoryNotEmptyException" error? Does cleaning the target directory make a difference ?

**Comment by EwenG** [comment]
I added the "badigeon.compile/extract-classes-from-dependencies" function on master. By combining badigeon.compile/compile and badigeon.compile/extract-classes-from-dependencies, you should now be able to extract all dependent classes without the need of clojure$slim. Let me know how this works out.

**Comment by hlolli** [comment]
Thanks a lot, I will check as soon as I can, latest in a week, deadline on
other projects.

**Comment by hlolli** [comment]
Before making a jar, I call

```Clojure
  (compile/compile '[panaeolus.all]
                   {:compile-path "target/classes"
                    :compiler-options {:disable-locals-clearing false
                                       :direct-linking true}
                    :classpath (classpath/make-classpath {:aliases []})})
  (compile/extract-classes-from-dependencies
   {:deps-map (assoc (deps-reader/slurp-deps "deps.edn")
                     :deps '{org.clojure/clojure {:mvn/version "1.10.0"}
                             org.slf4j/slf4j-api {:mvn/version "1.8.0-beta4"}})
    })
```

it's as if this has no effect at all, clojure.lang.Var isn't there and when I add clojure classes manually (a workaround I had worked on before) other classes are also missing (like nrepl/nrepl classes), then more classes. So basically I can't see that it did anything, maybe I'm using it wrong? I'm expecting to see the classes pop in target/classes, which is the default value, but they are neither there nor in the jar.

Also possibly unrelated. I'm unable to run a jar created from windows, did you test the jars on windows. I have no idea why this should be related to badigeon, because it all works fine with mac and linux and on windows running the classes directly, or extracting the jar-file work, but just calling `java -jar` says that my main class is missing, despite it being there. I'm bit lost with windows and it's possible that this bug is totally on my side.

**Comment by EwenG** [comment]
I forked panaeolus ([https://github.com/EwenG/panaeolus](https://github.com/EwenG/panaeolus)) and added a build.sh script.

`./build.sh`

clojure.lang.Var seems to be here

`ls target/classes/clojure/lang/Var.class`

A few things I noticed:

- The `clojure.core.specs.alpha` namespace must explicitly be added to `badigeon.compile/compile` because it is already loaded when `clojure.core/compile` is called. I will make  `badigeon.compile/compile` to add it automatically when it exists.

- You will probably have to copy `clojure/version.properties` to the classpath because it is needed by clojure.core: `(spit "target/classes/clojure/version.properties" (slurp (io/resource "clojure/version.properties")))`

**Comment by hlolli** [comment]
Thanks so much for testing my project!

I'm working on a PR on panaeolus, but so far, I've been struggling, first
with jna itself (which has a .so file that I had no idea about), then now
I'm battling with jline. Inside the following jar `org.jline/jline-terminal
"3.11.0"` are files /org/jline/utils/capabilities.txt,
/org/jline/utils/ansi.caps, /org/jline/utils/dumb.caps,
/org/jline/utils/screen.caps, /org/jline/utils/screen.caps,
/org/jline/utils/screen-256color.caps, /org/jline/utils/windows.caps,
/org/jline/utils/xterm.caps and /org/jline/utils/xterm-256color.caps. Since
these files are neither java nor native files, I'm not sure how the
badigeon way of exporting them from the jar would be? I would still
appreachiate a option for bundling all resources, or something like slimify
(exclude patterns). It would probably boil down to having an uberjar
option? I can research the bundle way of doing things, exporting many jar
modules, instead of uberjaring panaeolus.

**Comment by hlolli** [comment]
ah I see, of course I could just spit these out like you showcased with the
clojure/version.properties. Should be no problem to go around!

**Comment by hlolli** [comment]
Btw, everything works fine on Linux, but I seem to be unable to run this on
Windows

https://github.com/panaeolus/panaeolus/blob/5d9423fa8d8a1bb7d79ac4ea334dfbda0496bcae/scripts/build.clj#L26-L30

Windows is really irritating me already with strange special cases for \\
vs / in path seperators. It could be that it's the case, I'll have a deeper
look.

**Comment by EwenG** [comment]
The way I would do it is by making a bundle using badigeon.bundle/bundle: 
[https://github.com/EwenG/panaeolus/blob/master/scripts/build2.clj](https://github.com/EwenG/panaeolus/blob/master/scripts/build2.clj)

It creates a directory containing all your dependencies and an shell script to start the project.

The issue with an uberjar is that you have to deal with conflicting resources. Leiningen has some logic to merge conflicting files but I didn't want to replicate it.

The way you did it by manually adding resources to the uberjar works fine too.

**Comment by EwenG** [comment]
I will check the windows issues

**Comment by EwenG** [comment]
I added a namespace to extract everything from all dependencies:
[uberjar.clj](https://github.com/EwenG/badigeon/blob/master/src/badigeon/uberjar.clj)
Conflicting resources are simply discarded.

**Comment by EwenG** [comment]
Here is how you could user uberjar:
[build3.clj](https://github.com/EwenG/panaeolus/blob/master/scripts/build3.clj)

**Comment by hlolli** [comment]
thanks @EwenG I finally got it running from windows, there's a caveat with core.async, that its resources cannot be bundled, because doing so causes errors from evaluating the namespace twice. Took me a long time to figure it out.

But I must add that I still can't run the uberjar on windows, I can still run the main class from the budle output directory, which is ok for now for me. I get that the jar is corrupted, and even if MANIFEST.MF is wrong in some way, then `java -cp panaeolus.jar panaeolus.all` also tells me that the class panaeolus.all isn't there. So there's something annoying happening there.

For this ticket, I think this is solved, all the resources are bundled (with the danger that it can bring) so I'm very satisfied with the brevity of my build script now!

**Comment by EwenG** [comment]
The Main-Class line must be ended with a line break [here](https://github.com/panaeolus/panaeolus/blob/master/scripts/build2.clj#L24).
Apart from that, I successfuly built a jar and it seems to run on both linux and windows. (At least the main method is executed)

**Comment by hlolli** [comment]
Ok, that's good news, that you were able to run the main class, this is what I'm getting

```
PS C:\Users\User\Documents\panaeolus> $env:COMPILING_PANAEOLUS = '1'; clojure -A:jar -m build2
PS C:\Users\User\Documents\panaeolus> cd .\target\
PS C:\Users\User\Documents\panaeolus\target> ls


    Directory: C:\Users\User\Documents\panaeolus\target


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        6/30/2019   5:32 AM                classes
d-----        6/27/2019  10:09 AM                panaeolus-0.4.0-SNAPSHOT
-a----        6/30/2019   5:36 AM       40552382 panaeolus-0.4.0-SNAPSHOT.jar


PS C:\Users\User\Documents\panaeolus\target> java -jar .\panaeolus-0.4.0-SNAPSHOT\
Error: Unable to access jarfile .\panaeolus-0.4.0-SNAPSHOT\
PS C:\Users\User\Documents\panaeolus\target> java -jar .\panaeolus-0.4.0-SNAPSHOT.jar
Error: Invalid or corrupt jarfile .\panaeolus-0.4.0-SNAPSHOT.jar
PS C:\Users\User\Documents\panaeolus\target> java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
PS C:\Users\User\Documents\panaeolus\target> java -cp .\panaeolus-0.4.0-SNAPSHOT.jar panaeolus.all
Error: Could not find or load main class panaeolus.all
PS C:\Users\User\Documents\panaeolus\target>
```

And I added a newline at the end
```Clojure
 (str "Manifest-Version: 1.0" (System/lineSeparator) "Main-Class: panaeolus.all" (System/lineSeparator))
```

**Comment by EwenG** [comment]
Can you upload the jar file somewhere so I can try it ?

**Comment by hlolli** [comment]
https://static.hlolli.com/panaeolus-0.4.0-SNAPSHOT.jar

I uploaded it here, you can try

**Comment by EwenG** [comment]
The issue is that, when building on windows, the path separator in the jar file is "\\" instead of "/".
This should be fixed on master: [https://github.com/EwenG/badigeon/commit/1e28b19e6461d827e7c2ad579ee010b8dde332c8](https://github.com/EwenG/badigeon/commit/1e28b19e6461d827e7c2ad579ee010b8dde332c8)

**Comment by hlolli** [comment]
this is fixed in windows, thanks so much for your help!
